/Loki/twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 50
      joystick:
          topic   : teleop_joy/cmd_vel
          timeout : 0.5
          priority: 100
      keyboard:
        topic   : turtle1/cmd_vel
        timeout : 0.5
        priority: 80
      esd:
        topic   : lock_vel
        timeout : 0.5
        priority: 255
twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 50
      joystick:
          topic   : teleop_joy/cmd_vel
          timeout : 0.5
          priority: 100

/Odin/twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 50
      joystick:
          topic   : teleop_joy/cmd_vel
          timeout : 0.5
          priority: 100
      keyboard:
        topic   : turtle1/cmd_vel
        timeout : 0.5
        priority: 80
      esd:
        topic   : lock_vel
        timeout : 0.5
        priority: 255
